// Generated by CIRCT firtool-1.114.1
module BlinknCountRWTap(
  input        clock,
               reset,
               io_en,
               io_isAdd,
  output       io_out,
  output [3:0] io_count
);

  `ifndef SYNTHESIS
    initial
      force BlinknCountRWTap.counter.counter = 4'h1;
  `endif // not def SYNTHESIS
  myCounter counter (
    .clock  (clock),
    .reset  (reset),
    .out    (io_out),
    .bore   (io_en),
    .bore_1 (io_isAdd)
  );
  assign io_count = BlinknCountRWTap.counter.counter_probe;
endmodule

