// Generated by CIRCT firtool-1.114.1
`include "verification/layers-BlinknCountTap-Verification.sv"
`ifndef layers_BlinknCountTap_Verification_Assume
`define layers_BlinknCountTap_Verification_Assume
`endif // layers_BlinknCountTap_Verification_Assume
