// Generated by CIRCT firtool-1.114.1
module BlinknCount(
  input        clock,
               reset,
               io_en,
               io_isAdd,
  output       io_out,
  output [3:0] io_count
);

  myCounter counter (
    .clock         (clock),
    .reset         (reset),
    .out           (io_out),
    .io_count_bore (io_count),
    .bore          (io_en),
    .bore_1        (io_isAdd)
  );
endmodule

