// Generated by CIRCT firtool-1.114.1
module myCounter(
  input  clock,
         reset,
  output out,
  input  bore,
         bore_1
);

  wire [3:0] _add0_io_out;
  reg        en;
  reg  [3:0] counter;
  wire [3:0] counter_probe = counter;
  always @(posedge clock) begin
    if (reset) begin
      en <= 1'h0;
      counter <= 4'h0;
    end
    else begin
      en <= bore;
      if (en)
        counter <= _add0_io_out;
    end
  end // always @(posedge)
  myAdder add0 (
    .io_in0 (counter),
    .io_out (_add0_io_out),
    .bore   (bore_1)
  );
  assign out = &counter;
endmodule

